version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.3.2
    command: start-dev
    ports:
      - "127.0.0.1:9000:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin